### ISSUE TITLE
Duplicate jenkins-edit|view RB in online-team template

### ISSUE THREAD

**Issue by aslakknutsen** [fabric8io/fabric8-online#298]
Probably due to same rolebinding being defined in two different rb files:

https://github.com/fabric8io/fabric8-online/blob/master/packages/fabric8-online-team/src/main/fabric8/user-edit-rb.yml

https://github.com/fabric8io/fabric8-online/blob/master/packages/fabric8-online-team/src/main/fabric8/jenkins-edit-rb.yml

and 

https://github.com/fabric8io/fabric8-online/blob/master/packages/fabric8-online-team/src/main/fabric8/user-view-rb.yml

https://github.com/fabric8io/fabric8-online/blob/master/packages/fabric8-online-team/src/main/fabric8/jenkins-view-rb.yml

**Comment by jstrachan** [comment]
I think the https://github.com/fabric8io/fabric8-online/blob/master/packages/fabric8-online-team/src/main/fabric8/user-edit-rb.yml was meant to be the edit role for the current username; so that the user can create/edit jobs in jenkins. 

Though TBH I think to keep the jenkins namespace locked down we're gonna have to try something else; e.g. a fake edit role in the jenkins namespace; so that jenkins thinks the user has edit, but openshift does not ;)

For now lemme just remove the duplicate though

**Comment by jstrachan** [comment]
There's a duplicate here anyway for the jenkins namespace ;) https://github.com/fabric8io/fabric8-online/blob/master/packages/fabric8-online-jenkins/src/main/fabric8/user-edit-rb.yml so lemme remove that one from team
